# Generated by Django 3.2.7 on 2021-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchain_eth", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="block",
            name="transactions_updated",
            field=models.BooleanField(default=False),
        )
    ]
