# Generated by Django 3.2.7 on 2021-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchain_eth", "0002_block_transactions_updated")]

    operations = [
        migrations.AddField(
            model_name="block",
            name="number",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        )
    ]
