# Generated by Django 3.2.7 on 2021-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blockchain_eth", "0004_transaction_type")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="hash",
            field=models.CharField(default="", max_length=500, unique=True),
        )
    ]
